[tool.poetry]
name = "Media-bot"
version = "0.0.1"
description = "A project for fetching media from various sources into a telegram chat."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/reddit-media-bot"

[tool.poetry.dependencies]
python = ">=3.10, <4"
raven = "^6"
alembic = "^1"
requests = "^2"
beautifulsoup4 = "^4"

telethon = "^1"

toml = "^0"
youtube_dl = "^2021"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
