[tool.poetry]
name = "Python-media-bot"
version = "0.0.1"
description = "A project for fetching reddit media into a telegram chat."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/reddit-media-bot"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "6.10"
alembic = "1.0"

telethon = "^1.9"
python-telegram-bot = "^12.0.0b1"

SQLAlchemy = "^1.2"
sqlalchemy-utils = "^0.33"
psycopg2-binary = "^2.8"

toml = "^0.10"
youtube_dl = "^2019"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
