[tool.poetry]
name = "Python-media-bot"
version = "0.0.1"
description = "A project for fetching reddit media into a telegram chat."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/reddit-media-bot"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "^6"
alembic = "^1"
requests = "^2"
beautifulsoup4 = "^4"

telethon = "^1"

SQLAlchemy = "^1"
sqlalchemy-utils = "^0.36"
psycopg2-binary = "^2"

toml = "^0"
youtube_dl = "^2020"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
